### PR TITLE
Fixes the "PickLastInTuple" type error in "compose.ts" in TypeScript 4.2.x

### LINKED ISSUE #615: TypeScript 4.2.* can't type check utils/internal/compose.d.ts PickLastInTuple<T>
## Describe the bug
After updating from TypeScript 4.1.5 to 4.2.2 `msw` can no longer be type-checked with `tsc --noEmit`.

```
node_modules/msw/lib/types/utils/internal/compose.d.ts(6,65):
  error TS2344: Type 'PickLastInTuple<T>' does not satisfy the constraint '(...args: any) => any'.
    Type 'unknown' is not assignable to type '(...args: any) => any'.
```

I don't think I even use that type, but because it is included in `msw/index.d.ts` TypeScript wants it to pass :/

## Environment

- `msw: 0.26.2`
- `nodejs: 14.13.0`
- `npm: 7.5.4`
- `typescript: 4.2.2`

## To Reproduce
1. Install `msw@0.26.2` and `typescript@4.2.2`
2. Create a file that imports anything from `msw`
3. Try to type-check said file with `tsc --noEmit`

## Expected behavior
TypeScript can type-check `msw`, in specific `PickLastInTuple<T>`

### PR DESCRIPTION
**Pull request by kettanaito**
## GitHub

- Fixes #615

## Resources

- https://dev.to/miracleblue/how-2-typescript-get-the-last-item-type-from-a-tuple-of-types-3fh3

### CODE REVIEW

**Comment by crunchy244** [comment]
I don't mean to intrude but you can also use some very cool new TS features to get tuple and trailing types.

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#variadic-tuple-types
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#non-trailing-rests

```ts
type First<T extends any[]> = T extends [infer U, ...any[]] ? U : never;
type Last<T extends any[]> = T extends [...any[], infer U] ? U : never;
type Tail<T extends any[]> = T extends [any, ...infer U] ? U : never;
```

**Comment by kettanaito** [comment]
Hey, @rabelloo. Thanks for the suggestion. That's how the type was implemented before. Using it this way produces a type violation:

```ts
type LastInTuple<T extends any[]> = T extends [...any[], infer LastArg]
  ? LastArg
  : never

type FirstFnParameterType<Functions extends ArityOneFunction[]> = Parameters<
  LastInTuple<Functions>
>[any]
```

```
Type 'unknown' is not assignable to type '(...args: any) => any'.ts(2344)
```

There must be something wrong with how TypeScript checks the return type of using that `LastInTuple` wrapped in another generic.

**Comment by dylan-sr** [comment]
Just a heads up that copying this change on to v0.27.0 along with typescript 4.2.2 and awesome-typescript-loader 5.2.1
While trying to build my project I'm getting the following errors
```
ERROR in [at-loader] ./node_modules/msw/lib/types/utils/internal/compose.d.ts:38:22 
    TS1183: An implementation cannot be declared in ambient contexts.
ERROR in [at-loader] ./node_modules/msw/lib/types/utils/internal/compose.d.ts:39:23 
    TS1183: An implementation cannot be declared in ambient contexts.
ERROR in [at-loader] ./node_modules/msw/lib/types/utils/internal/compose.d.ts:40:54 
    TS1183: An implementation cannot be declared in ambient contexts.
```

However using the change suggested here https://github.com/mswjs/msw/issues/615#issuecomment-789617698 as the compose.d.ts instead it builds without any issue.
```
declare type ArityOneFn = (arg: any) => any;
declare type PickLastInTuple<T extends any[]> = T extends [
    ...rest: infer U,
    argn: infer L
] ? L : never;
type ParametersOrNot<T> = T extends (...args: any[]) => any ? Parameters<T> : never;
declare type FirstFnParameterType<T extends any[]> = ParametersOrNot<PickLastInTuple<T>>[any];
declare type LastFnParameterType<T extends any[]> = ReturnType<T[0]>;
/**
 * Composes a given list of functions into a new function that
 * executes from right to left.
 */
export declare function compose<T extends ArityOneFn[], LeftReturnType extends FirstFnParameterType<T>, RightReturnType extends LastFnParameterType<T>>(...fns: T): (...args: LeftReturnType extends never ? never[] : [LeftReturnType]) => RightReturnType;
export {};
```

**Comment by kettanaito** [comment]
@dylan-sr, that's entirely strange. TypeScript 4.2.2 gives me no errors with this pull request. Can it be a loader issue? I see some tools warning about TS 4.2 not being officially supported. Could you double-check if that's the case with awesome-typescript-loader?

**Comment by kettanaito** [comment]
If the issue indeed persists, may I kindly ask you to do a follow-up pull request?
