### ISSUE TITLE
TypeScript 4.2.* can't type check utils/internal/compose.d.ts PickLastInTuple<T>

### ISSUE THREAD

**Issue by crunchy244** [mswjs/msw#615]
## Describe the bug
After updating from TypeScript 4.1.5 to 4.2.2 `msw` can no longer be type-checked with `tsc --noEmit`.

```
node_modules/msw/lib/types/utils/internal/compose.d.ts(6,65):
  error TS2344: Type 'PickLastInTuple<T>' does not satisfy the constraint '(...args: any) => any'.
    Type 'unknown' is not assignable to type '(...args: any) => any'.
```

I don't think I even use that type, but because it is included in `msw/index.d.ts` TypeScript wants it to pass :/

## Environment

- `msw: 0.26.2`
- `nodejs: 14.13.0`
- `npm: 7.5.4`
- `typescript: 4.2.2`

## To Reproduce
1. Install `msw@0.26.2` and `typescript@4.2.2`
2. Create a file that imports anything from `msw`
3. Try to type-check said file with `tsc --noEmit`

## Expected behavior
TypeScript can type-check `msw`, in specific `PickLastInTuple<T>`

**Comment by kettanaito** [comment]
@rabelloo, thank you for reporting this! The issue is fixed and will be released in the next patch version.

**Comment by ngame2011** [comment]
A temporary solution that worked for me:
```
type ParametersOrNot<T> = T extends (...args: any[]) => any ? Parameters<T> : never;

declare type FirstFnParameterType<T extends any[]> = ParametersOrNot<PickLastInTuple<T>>[any];
```
