### ISSUE TITLE
"cookie" module has no default export

### ISSUE THREAD

**Issue by cgatian** [mswjs/msw#321]
## Describe the bug
This is more of a convenience issue, than bug.

Performing a build with TypeScript 3.9.5 with `allowSyntheticDefaultImports` disabled displays:
> ERROR in node_modules/msw/lib/types/context/cookie.d.ts:1:8 - error TS1192: Module '"<path>/node_modules/@types/cookie/index"' has no default export.

Now the issue is because my TypeScript config is strict, and I can modify it to either ignore libraries or allow the synthetic import. However, it might be better to update areas of the code that are doing this:

```typescript
import cookieUtils from 'cookie'
```
To

```typescript
import { parse } from 'cookie'
```
Since the [library definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cookie/index.d.ts) accurately reflect no default export on the [cookie](https://github.com/jshttp/cookie/blob/master/index.js) package.

I also could have all this wrong... I don't claim to be an expert in any of this

## Environment

- `msw: 0.20.1`
- `nodejs: 14.2.0`
- `npm: 6.14.5`

> Please also provide your browser version.

## To Reproduce
1. Configure TypeScript compilation without `allowSyntheticDefaultImports`
2. Import `import { setupWorker, rest } from 'msw';` somewhere in code
3. TypeScript compilation issue

## Expected behavior
No compilation errors

**Comment by kettanaito** [comment]
Hey, @cgatian! Thanks for letting us know about this.

I've tackled this by setting `allowSyntheticDefaultImports: false` in our `tsconfig.json`. This change has reported this, and some other violations, which I've addressed. Expect the changes to be merged soon.

**Comment by cgatian** [comment]
Thanks for being open to the suggestion. This should improve the quality of life for consumers of this lib. 👍

**Comment by kettanaito** [comment]
The changes are published in [`0.20.2`](https://github.com/mswjs/msw/releases/tag/v0.20.2). Please update and let us know that it compiles without TypeScript errors now.

**Comment by cgatian** [comment]
Works great. Thank you!
